update_frequency: 5.0 #2.0
publish_frequency: 5.0 #2.0
transform_tolerance: 5.0 #1.0

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.3, 0.2], [0.3, -0.2], [-0.15, -0.2], [-0.15, 0.2]]
footprint_padding: 0.02

# traversability_layer:
#   enabled: true
#   map_topic: /traversability_to_occupancy/traversability_grid
#   subscribe_to_updates: true

# obstacle_layer:
#   enabled: true
#   observation_sources: point_cloud_sensor
#   point_cloud_sensor: 
#     data_type: PointCloud2
#     topic: /beyond_rover/beyond_rover_front_camera/depth/points
#     marking: true
#     clearing: true
#     min_obstacle_height: 0.15 #0.03
#     max_obstacle_height: 3.0

inflation_layer:
  enabled: true
  inflation_radius: 0.25
  cost_scaling_factor: 15.0

# # observation_sources: laser_scan
# observation_sources: point_cloud_sensor

# # laser_scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: 0.03, max_obstacle_height: 3.0}
# point_cloud_sensor: {data_type: PointCloud2, topic: /beyond_rover/beyond_rover_front_camera/depth/points, marking: true, clearing: false, min_obstacle_height: 0.03, max_obstacle_height: 3.0}
